# Configuration for IR → SAR Training

# Image settings
img_size: 48

# Training parameters
batch_size: 16
learning_rate: 0.001
num_epochs: 20

# Dataset split
train_split: 0.2
val_split: 0.2
test_split: 0.6

# Paths
data_path: "/scale/user/mtannaou/alternance/src/IR_to_SAR/data_sar_ir_pkl/ir_sar_pairs_v1.pkl"
save_dir: "/scale/user/mtannaou/alternance/src/IR_to_SAR/ML_IR_SAR/train_history_ir_sar"

# Early stopping
early_stop_patience: 10
early_stop_delta: 0.0005

# Plotting
start_epoch: 1
plot_interval: 5

# Device
accelerator: "auto"
devices: 1   # If you want GPU: use "1", for CPU: "cpu" or "auto"

# Scheduler
scheduler_every_n_epochs: 1
