# Configuration for IR → SAR Training

# Image settings
img_size: 256
norm : "z_score"
barycenter : "no"
augmentation : True
drop_nan_sar : True
in_channels: 1     # ir channel 
out_channels: 1

# Training parameters
batch_size: 32
learning_rate: 0.0001
num_epochs: 200
dropout : 0.3

# Dataset split
train_split: 0.7
val_split: 0.29
test_split: 0.01
# Paths
data_path: "/scale/user/mtannaou/alternance/src/IR_to_SAR/data_sar_ir_pkl/ir_sar_pairs_v1.pkl"
save_dir: "/scale/user/mtannaou/alternance/src/IR_to_SAR/ML_IR_SAR/train_history_ir_sar"

# Early stopping
early_stop_patience: 30
early_stop_delta: 0.0001

# Plotting
start_epoch: 0
plot_interval: 5
num_val_exemples : 10

# Device
accelerator: "gpu"
devices: [2]   # 

# Scheduler
scheduler_every_n_epochs: 10
